@url = http://localhost:3000

###
GET {{url}}/materias

###
GET {{url}}/materias/1

###
POST {{url}}/materias
Content-Type: application/json

{
  "materia": "Física",
  "codigo": "FIS",
  "año": 2024
}

###
PUT {{url}}/materias/1
Content-Type: application/json

{
  "materia": "Química",
  "codigo": "QUI",
  "año": 2024
}

###
DELETE {{url}}/materias/1