@url = http://localhost:3000

### 
GET {{url}}/usuarios


### 
GET {{url}}/usuarios/1


### 
POST {{url}}/usuarios
Content-Type: application/json

{
  "username": "exequielmendoza",
  "email": "exequiel@gmail.com",
  "contraseña": "Exequiel123!!"
}

### 
PUT {{url}}/usuarios/1
Content-Type: application/json

{
  "username": "fernando_garcia",
  "email": "fernando@hotmail.com",
  "contraseña": "Fernando123!!"
}

### 
DELETE {{url}}/usuarios/1


